import Head from 'next/head'
import Image from 'next/image'
import { Component } from 'react'
import styles from '../styles/Home.module.css'
import {Row,Col, Button } from 'antd';
import Link from 'next/link';
import { useRouter } from 'next/router'
import profilePic from '../public/demo.png'

class Home extends Component{
  constructor(props){
    super(props);
    this.state = {
        price:"45元/月"
    }
}

  static getInitialProps({query}) {
    return {query}
  }

  componentDidMount(){
    let {price} = this.props.query;
    if(price){
      this.setState({
        price
      })
    }
  }

  submit =  async () => {
    const router = useRouter()
    console.log(router.query);
  
    const res = await fetch(`https://zhangwei-7gl977h782ef503e-1306346100.ap-shanghai.service.tcloudbase.com/rest-api/v1.0/quotation`)
    const data = await res.json();
   
    if(!data){
      alert("提交失败，请检查当前网络环境")
    }else{
      console.log(data)
    }
  }
  render(){
    let {price} = this.state;
    return(
      <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Image src={profilePic} alt="Picture of the author" layout="fill"/>
      </main>
      
      <Link href={`/form?price=${price}`}><a>
      <div className={styles.bottomBtn}>
        <Row gutter={16}>
        <Col span={16}>
           会员价 {price}
        </Col>
        <Col span={8}>
        <Button type="primary"> 立即购买</Button>
        </Col>
        </Row>
      </div>
      </a></Link>
    </div>
    )
  }
}
export default Home;